-- SELECCIONAR UN USUARIO
SELECT 
    NOMBRE, APELLIDO, USERNAME, PASS, EMAIL, TELEFONO, DIRECCION, FOTOGRAFIA, GENERO, 
    FECHA_NACIMIENTO, FECHA_REGISTRO, FECHA_VALIDACION, ESTADO, DESCRIPCION AS TIPO 
FROM 
    Usuario U, Tipo T
WHERE 
    U.COD_TIPO = T.COD_TIPO AND 
    USERNAME = :username;