CREATE VIEW VIEW_USUARIO AS 
SELECT 
    COD_USUARIO, NOMBRE, APELLIDO, USERNAME, PASS, EMAIL, 
    TELEFONO, DIRECCION, FOTOGRAFIA, GENERO, FECHA_NACIMIENTO, 
    FECHA_REGISTRO, FECHA_VALIDACION, ESTADO, DESCRIPCION AS TIPO
FROM 
    USUARIO U, TIPO T
WHERE 
    U.COD_TIPO = T.COD_TIPO;